version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: payment_postgres
    restart: always
    ports:
      - "5445:5432"
    environment:
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: payment_db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: payment_rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mongodb:
    image: mongo:7.0
    container_name: risk_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: riskdb
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: