spring:
  application:
    name: ms-payment-service
  datasource:
    url: jdbc:postgresql://localhost:5445/payment_db
    username: payment
    password: 1234

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  jpa:
    properties:
      hibernate:
        format_sql: true

    show-sql: true
    hibernate:

      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db/change-master.yml

server:
  port: 8083


client:
  ms-auth-service:
    url: http://localhost:8081
  ms-account-service:
    url: http://localhost:8082